### PR TITLE
demux: add AnimDecoder test

### PR DESCRIPTION
**Pull request by MathieuDuponchelle**
Hey, I was simply trying out the API as a unit test, and figured it made sense to upstream it :)

### CODE REVIEW

**Comment by qnighy** [comment]
Could you avoid `MaybeUninit` for now or bump the MSRV in the CI?

**Comment by MathieuDuponchelle** [comment]
> Could you avoid `MaybeUninit` for now or bump the MSRV in the CI?

Sure, removed usage, I don't think bumping for a unit test is necessary :)

**Review by qnighy — COMMENTED** [review]
Thanks! The code is ok.

Though I'm concerned about the test image; if I understand correctly, Nyan Cat is not a free-to-use character. I would appreciate it if you can find a better one. Otherwise I will find an alternative later.

**Comment by MathieuDuponchelle** [comment]
@qnighy hm good point, I simply googled for "animated webp sample" fwiw. If you can find one you would prefer using it might be best if you for one yes :)

**Comment by MathieuDuponchelle** [comment]
generated one myself with GStreamer

**Review by qnighy — APPROVED** [review]
Looks fine. Thanks!

**Comment by blaind** [comment]
If interested, I've published an initial version of webp animation crate based on WebPAnim* functions published by libwebp-sys2-rs. Located at https://crates.io/crates/webp-animation

**Pull request merged**
