### PR TITLE
Reference libwebp as a submodule instead of committed code

### PR DESCRIPTION
**Pull request by blaind**
Instead of committing the libwebp code directly into repository, it can be referenced as a submodule. Current ref to v1.2.0 (see commit from https://chromium.googlesource.com/webm/libwebp/+/refs/tags/v1.2.0)

I also modified the github action for recursive submodule according to docs at https://github.com/marketplace/actions/checkout-submodules (couldn't test).

### CODE REVIEW

**Comment by qnighy** [comment]
So this is the difference:

```
$ LANG=C diff -ru c_src c_src-git
Only in c_src-git: .git
Only in c_src-git: .gitattributes
Only in c_src-git: .gitignore
Only in c_src-git: .mailmap
Only in c_src: Makefile.in
Only in c_src: aclocal.m4
Only in c_src: ar-lib
Only in c_src: compile
Only in c_src: config.guess
Only in c_src: config.sub
Only in c_src: configure
Only in c_src: depcomp
Only in c_src-git/doc: TODO
Only in c_src/examples: Makefile.in
Only in c_src/extras: Makefile.in
Only in c_src/imageio: Makefile.in
Only in c_src: install-sh
Only in c_src: ltmain.sh
Only in c_src-git/m4: .gitignore
Only in c_src/m4: libtool.m4
Only in c_src/m4: ltoptions.m4
Only in c_src/m4: ltsugar.m4
Only in c_src/m4: ltversion.m4
Only in c_src/m4: lt~obsolete.m4
Only in c_src/man: Makefile.in
Only in c_src: missing
Only in c_src/src: Makefile.in
Only in c_src/src/dec: Makefile.in
Only in c_src/src/demux: Makefile.in
Only in c_src/src/dsp: Makefile.in
Only in c_src/src/enc: Makefile.in
Only in c_src/src/mux: Makefile.in
Only in c_src/src/utils: Makefile.in
Only in c_src/src/webp: config.h.in
```

I forgot why I didn't choose submodule in the first place, but it looks fine as long as it compiles.

**Review by qnighy — COMMENTED** [review]
Looks almost fine. Could you also remove `.gitattributes`? It only contains the line to tell `linguist` to count `c_src` as vendored and it's no longer necessary.

**Review by qnighy — APPROVED** [review]
I can remove `.gitattributes` myself so let's merge it

**Comment by blaind** [comment]
Great, thank you! :)

**Comment by blaind** [comment]
Would it be possible to make a release that contains this change?

**Pull request merged**
